version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: elite-replicas
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      # Add other environment variables here or use env_file
    # Uncomment and configure if using a database
    # depends_on:
    #   - db
    #   - redis
    # networks:
    #   - app-network
    # volumes:
    #   - ./uploads:/app/uploads
    #   - /app/node_modules

  # Uncomment and configure if using a database
  # db:
  #   image: postgres:15
  #   container_name: elite-replicas-db
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_USER: ${DB_USER}
  #     POSTGRES_PASSWORD: ${DB_PASSWORD}
  #     POSTGRES_DB: ${DB_NAME}
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - app-network

  # redis:
  #   image: redis:7
  #   container_name: elite-replicas-redis
  #   restart: unless-stopped
  #   command: redis-server --requirepass ${REDIS_PASSWORD}
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   networks:
  #     - app-network

# volumes:
#   postgres_data:
#   redis_data:

# networks:
#   app-network:
#     driver: bridge
